# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-08 04:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmm',
            name='ems',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), null=True, size=None),
        ),
        migrations.AddField(
            model_name='hmm',
            name='states',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='hmm',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hmm',
            name='trans',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), null=True, size=None),
        ),
    ]
