# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20160319_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='bias_at_answer',
            field=models.IntegerField(default=0, verbose_name='bias'),
        ),
    ]
