# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20160419_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='bias_at_answer',
            field=models.FloatField(default=0, verbose_name='bias'),
        ),
    ]
