# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-17 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20160419_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='gradient_at_answer',
            field=models.FloatField(default=0, verbose_name='Gradient'),
        ),
    ]
