# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 04:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_worker_id', models.CharField(blank=True, max_length=255, verbose_name='Amazon worker id')),
                ('aws_key', models.CharField(max_length=255, null=True, unique=True, verbose_name='Amazon worker key')),
                ('expected_bias', models.CharField(choices=[('G', 'Good'), ('R', 'Random'), ('M', 'Malicious')], default='R', max_length=1, verbose_name='Bias as per instruction')),
                ('bias', models.IntegerField(default=0, verbose_name='bias')),
                ('uncertain_count', models.IntegerField(default=0, verbose_name='uncertainity count')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username'),
        ),
    ]
