# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 21:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('aws_worker_id', models.CharField(blank=True, max_length=255, verbose_name='Amazon worker id')),
                ('aws_key', models.CharField(max_length=255, null=True, unique=True, verbose_name='Amazon worker key')),
                ('expected_bias', models.CharField(choices=[('G', 'Good'), ('R', 'Random'), ('M', 'Malicious')], default='R', max_length=1, verbose_name='Bias as per instruction')),
                ('bias', models.IntegerField(default=0, verbose_name='bias')),
                ('uncertain_count', models.IntegerField(default=0, verbose_name='uncertainity count')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assignment_id', models.CharField(max_length=255, null=True, unique=True, verbose_name='Amazon Assignment Id')),
                ('time_of_completion', models.DateTimeField(null=True)),
                ('time_due_at', models.DateTimeField(null=True)),
                ('url_turk_submission', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('hit_id', models.CharField(max_length=255, null=True, unique=True, verbose_name='Amazon HIT Id')),
                ('url', models.CharField(default='', max_length=255, verbose_name='url for hit')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('frame_height', models.IntegerField(default=500)),
                ('amount', models.IntegerField(default=0.01)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='hit',
            field=models.ManyToManyField(to='turk.HIT'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ManyToManyField(to='turk.AmazonWorker'),
        ),
    ]
