# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 17:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonworker',
            name='aws_key',
        ),
        migrations.AlterField(
            model_name='hit',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='hit',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='url',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='url for hit'),
        ),
    ]
