# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0002_auto_20160219_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='hit',
        ),
        migrations.AddField(
            model_name='assignment',
            name='hit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='turk.HIT'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='turk.AmazonWorker'),
            preserve_default=False,
        ),
    ]
