# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0003_auto_20160219_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonworker',
            name='aws_worker_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Amazon worker id'),
        ),
    ]
