# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0004_auto_20160226_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonworker',
            name='expected_bias',
        ),
        migrations.AddField(
            model_name='hit',
            name='expected_bias',
            field=models.CharField(choices=[('G', 'Good'), ('R', 'Random'), ('M', 'Malicious')], default='R', max_length=1, verbose_name='Bias as per instruction'),
        ),
    ]
