# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0005_auto_20160320_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonworker',
            name='uncertain_count',
            field=models.IntegerField(default=1, verbose_name='uncertainity count'),
        ),
    ]
