# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0006_auto_20160419_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonworker',
            name='bias',
            field=models.FloatField(default=0, verbose_name='bias'),
        ),
    ]
