# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0007_auto_20160419_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonworker',
            name='classification',
            field=models.CharField(choices=[('G', 'Good'), ('R', 'Random'), ('M', 'Malicious')], default=None, max_length=1, null=True, verbose_name='Classification as GRM'),
        ),
    ]
