# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0008_amazonworker_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonworker',
            name='exit_bias',
            field=models.FloatField(default=0, verbose_name='Exit bias'),
        ),
    ]
