# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-18 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0009_amazonworker_exit_bias'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonworker',
            name='exit_round',
            field=models.IntegerField(null=True, verbose_name='Exit round'),
        ),
    ]
