# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-08 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turk', '0010_amazonworker_exit_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_id',
            field=models.CharField(max_length=255, null=True, verbose_name='Amazon Assignment Id'),
        ),
    ]
